### ISSUE TITLE
Inbox constantly refreshing

### ISSUE THREAD

**Issue by tprotopopescu** [TfTHacker/obsidian-readwise-inbox#3]
Thank you so much for this! I have been trying to create some kind of system like this (with far less knowledge of what I am doing :) ). 

I don't know if this is an Obsidian 1.0 issue since I only started using this after the update but I find that the inbox query I have is constantly refreshing, even when I modify a totally unrelated note, i.e. not one that is part of the query. Basically if I make any edits in any note that triggers a refresh of the inbox. 

Is this intended?

**Comment by phillipjohnston** [comment]
As far as I know, that's the behavior of Dataview. You can turn it off in the Dataview settings by disabling "Automatic View Refreshing", or you can tweak the Refresh Interval (I have 5s currently).

**Comment by tprotopopescu** [comment]
Thank you, disabling automatic view refreshing did it. I should have thought of that, but I only installed dataview so I could use readwise inbox :). Thanks again.
