### ISSUE TITLE
Text not copying to clipboard

### ISSUE THREAD

**Issue by tprotopopescu** [TfTHacker/obsidian-readwise-inbox#4]
Since the update to Obsidian to 1.2.7 none of the copy to clipboard buttons (B, A, T) work. Pressing triggers the message 'copied to clipboard, but nothing is actually saved to the clipboard. The X button still works to mark an annotation as done. 

It does not seem to be an issue with the buttons plugin, there is nothing on their github issues about that not working since the update.

**Comment by phillipjohnston** [comment]
I am now on 1.2.7 and copy buttons are working for me...

**Comment by tprotopopescu** [comment]
Thanks! That suggests it is something about my setup. I tried disabling all of the plugins I use, expect for dataview, buttons and readwise, and that didn't help. The console output I get when pressing the clipboard buttons is "Uncaught (in promise) DOMException: Write permission denied." 

I would welcome any suggestions for where to look to track this down.

**Comment by phillipjohnston** [comment]
What’s the installer version? I’m still on 1.1.5. Maybe that’s a critical difference.Cheers,PhillipOn May 8, 2023, at 08:57, tprotopopescu ***@***.***> wrote:﻿
Thanks! That suggests it is something about my setup. I tried disabling all of the plugins I use, expect for dataview, buttons and readwise, and that didn't help. The console output I get when pressing the clipboard buttons is "Uncaught (in promise) DOMException: Write permission denied."
I would welcome any suggestions for where to look to track this down.

**Comment by tprotopopescu** [comment]
That could be, I'm on 1.2.7.

**Comment by TfTHacker** [comment]
Hi there. Sorry to hear you are having this problem. I am on version 1.2.8, installer 1.1.9, and just tested the Readwise inbox and it was working for me.

I am on the Mac platform. You?

**Comment by tprotopopescu** [comment]
I am on linux, Opensuse 15.4.

**Comment by TfTHacker** [comment]
Hmmm I am not currently using Linux. Can you open the debugger in Obsidian to see if any error messages go to the console?

**Comment by tprotopopescu** [comment]
I get this message in the obsidian console: 

"Uncaught (in promise) DOMException: Write permission denied."

**Comment by tprotopopescu** [comment]
I just updated to 1.2.8 (for some reason I thought it was an insider build...) and the copy buttons are working again for me!

Thanks for taking the time to respond, and creating this (and text transporter, which was one of my fallback for copying annotations :) )

**Comment by TfTHacker** [comment]
That is a relief. I am sure it was a bit between obsidian and Linux based on the error message you reported, but I really wasn't sure how to resolve it. So I am glad there is some client fix.
